[package]
name = "mhw_planner"
version = "0.1.0"
authors = ["Scott Harper <orcein@gmail.com>"]
edition = "2018"

# Custom build script, executed before(?) the build
# build = "build.rs"

[dependencies]
reqwest = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
# failure = "0.1.5"
scraper = "*"

# iui = "0.3"

# orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk.git" }
# orbtk = "0.2.27"

# conrod = { version = "0.61.0", features = ["glium", "winit"] }

# azul = { git = "https://github.com/maps4print/azul" }

# [dependencies.sdl2]
# builtin = true

gfx = "0.17"
gfx_window_glutin = "0.28"
glutin = "0.19"
imgui = {version = "0.0.23-pre", path = "../imgui-rs/"}
imgui-gfx-renderer = {version = "0.0.23-pre", path = "../imgui-rs/imgui-gfx-renderer/"}
imgui-winit-support = {version = "0.0.23-pre", path  = "../imgui-rs/imgui-winit-support/"}
